### ISSUE TITLE
Arrows are backwards?

### ISSUE THREAD

**Issue by StevenTCramer** [Velorien/DependencyGraphDrawer#2]
See https://www.ibm.com/docs/en/rsm/7.5.0?topic=diagrams-dependency-relationships for good explanation. 

If `Client.csproj` has a `ProjectReference` to `Supplier.csproj` it would be stated in plantuml as `Client --> Supplier`  
and read as "Client uses Supplier"

Yet in the diagram being generated the arrows are backwards, current `Supplier --> Client`

**Comment by Velorien** [comment]
Usually when I draw arrows, I'm trying to represent the _data flow_, but you're right, this is a _dependency_ graph drawer. I'll change this soon-ish ;)

**Comment by Velorien** [comment]
Took me long enough, but this is changed in 0.9.4. Thanks for your feedback!
